title: Klipper Guide
description: A Klipper guide written by Glenn Kerselaers
theme: just-the-docs

url: https://glenn-kerselaers.github.io

aux_links:
  Template Repository: https://github.com/Glenn-Kerselaers/Glenn-Kerselaers.github.io
